kind: ConfigMap
metadata:
  name: burrow-config
  namespace: kafka 
apiVersion: v1
data:
  burrow.toml: |-
    [general]
    pidfile="burrow.pid"
    #stdout-logfile="burrow.out"

    [logging]
    level="debug"

    # logs to stdout by default
    #[logging]
    #filename="logs/burrow.log"
    #level="info"
    #maxsize=100
    #maxbackups=30
    #maxage=10
    #use-localtime=false
    #use-compression=true

    [zookeeper]
    servers=[ "zookeeper-0.zookeeper-service:2181", "zookeeper-1.zookeeper-service:2181", "zookeeper-2.zookeeper-service:2181" ]
    #root-path="/burrow"
    timeout=6

    [client-profile.test]
    client-id="burrow-test"
    #kafka-version="2.1.2"
    kafka-version="2.0.1"
    #sasl="mysasl"

    #[sasl.mysasl]
    #username="burrow"
    #password="burrow"
    #handshake-first=true

    [cluster.mykafka]
    class-name="kafka"
    client-profile="test"
    servers=[ "kafka-0.kafka-service:9092", "kafka-1.kafka-service:9092", "kafka-0.kafka-service:9092" ]
    topic-refresh=120
    offset-refresh=20

    [consumer.myconsumer]
    class-name="kafka"
    cluster="mykafka"
    servers=[ "kafka-0.kafka-service:9092", "kafka-1.kafka-service:9092", "kafka-0.kafka-service:9092" ]
    client-profile="test"
    #group-blacklist=""
    #group-whitelist=".*"

    #used for ZK-committed offsets (i.e. older consumers)
    #[consumer.zk]
    #class-name="kafka_zk"
    #cluster="mykafka"
    #servers=[ "zookeeper-0.zookeeper-service:2181", "zookeeper-1.zookeeper-service:2181", "zookeeper-2.zookeeper-service:2181" ]
    #zookeeper-timeout=30
    #group-blacklist=""
    #group-whitelist=".*"

    [httpserver.default]
    address=":8000"

    [storage.mystorage]
    class-name="inmemory"
    workers=20
    intervals=15
    expire-group=604800
    min-distance=1
