kind: ConfigMap
metadata:
  name: burrow-config
  namespace: producer-consumer 
apiVersion: v1
data:
  burrow.toml: |-
    [general]
    pidfile="burrow.pid"
    #stdout-logfile="burrow.out"

    # logs to stdout by default
    #[logging]
    #filename="logs/burrow.log"
    #level="info"
    #maxsize=100
    #maxbackups=30
    #maxage=10
    #use-localtime=false
    #use-compression=true

    [zookeeper]
    servers=[ "zookeeper-0.zookeeper-service.kafka.svc.cluster.local:2181", "zookeeper-1.zookeeper-service.kafka.svc.cluster.local:2181", "zookeeper-2.zookeeper-service.kafka.svc.cluster.local:2181" ]
    timeout=6

    [cluster.mykafka]
    class-name="kafka"
    servers=[ "kafka0.kafka-service.kafka.svc.cluster.local:9092", "kafka1.kafka-service.kafka.svc.cluster.local:9092", "kafka2.kafka-service.kafka.svc.cluster.local:9092" ]
    topic-refresh=60
    offset-refresh=30

    [consumer.myconsumer]
    class-name="kafka"
    cluster="mykafka"
    servers=[ "kafka0.kafka-service.kafka.svc.cluster.local:9092", "kafka1.kafka-service.kafka.svc.cluster.local:9092", "kafka2.kafka-service.kafka.svc.cluster.local:9092" ]
    client-profile="test"
    group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
    group-whitelist=""

    #[consumer.zk]
    #class-name="kafka_zk"
    #cluster="mykafka"
    #servers=[ "zookeeper-0.zookeeper-service.kafka.svc.cluster.local:2181", "zookeeper-1.zookeeper-service.kafka.svc.cluster.local:2181", "zookeeper-2.zookeeper-service.kafka.svc.cluster.local:2181" ]
    #zookeeper-timeout=30
    #group-blacklist=""
    #group-whitelist=""

    [httpserver.default]
    address=":8000"

    [storage.mystorage]
    class-name="inmemory"
    workers=20
    intervals=15
    expire-group=604800
    min-distance=1
