apiVersion: apps/v1
kind: Deployment
metadata:
  name: burrow
  namespace: producer-consumer 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burrow
  template:
    metadata:
      labels:
        app: burrow
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: zk-node
                operator: In
                values: ["true"]
      containers:
      - name: burrow
        image: solsson/burrow
        ports:
        - name: api
          containerPort: 8000
        volumeMounts:
        - name: config
          mountPath: /etc/burrow
        env:
        - name: BURROW_ADDR
          value: http://0.0.0.0:8000
        - name: API_VERSION
          value: "3"
        - name: METRICS_ADDR
          value: 0.0.0.0:8080
        - name: INTERVAL
          value: "30"
      volumes:
      - name: config
        configMap:
          name: burrow-config
